name: boqcalc_app
description: BoQCalc — расчёт объёмов и смета (web/mobile)
publish_to: 'none'
version: 0.3.0+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  path_provider: ^2.1.4
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
